services:
  rabbitmq:
    image: rabbitmq:4.0.3-alpine
    environment:
      # 100MB max frame size
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit max_message_size 104857600
    ports:
      - "${RABBITMQ_HOST_PORT}:${RABBITMQ_CONTAINER_PORT}"
      - "${RABBITMQ_DASHBOARD_HOST_PORT}:${RABBITMQ_DASHBOARD_CONTAINER_PORT}"
    networks:
      - backend_network
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "ping" ]
      interval: 5s
      timeout: 10s
      retries: 5
  postgres:
    image: postgres:17.1-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_CONTAINER_PORT}
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./sql_scripts:/docker-entrypoint-initdb.d/
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - backend_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB_NAME} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 10s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - ${PGADMIN_HOST_PORT}:${PGADMIN_CONTAINER_PORT}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend_network

  aspnet_server:
    build:
      context: .
      dockerfile: ./aspnet_server/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - ${ASPNET_HOST_PORT}:${ASPNET_CONTAINER_PORT}
    environment:
      - ASPNETCORE_URLS=http://+:3000
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_CONTAINER_PORT}
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB_NAME}
    networks:
      - backend_network

  rust_compressor:
    build:
      context: .
      dockerfile: ./rust_compressor/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_CONTAINER_PORT}
    networks:
      - backend_network

  sveltekit_server:
    build:
      context: .
      dockerfile: ./sveltekit_server/Dockerfile
    ports:
      - ${SVELTEKIT_HOST_PORT}:${SVELTEKIT_CONTAINER_PORT}
    # sveltekit overrides docker defined ports above with env variable `PORT` 
    environment:
      PORT: ${SVELTEKIT_HOST_PORT}
    networks:
      - backend_network

networks:
  backend_network:


volumes:
  pg_data:
  pgadmin_data:
