syntax = "proto3";

package compression.protobuf;

option csharp_namespace = "Compression.Protobuf";

enum Codec {
  H264 = 0;
  H265 = 1;
}

message CompressionRequest {
  // input binary data
  bytes video_bytes = 1;
  Codec codec = 2;
}

message CompressionResponse {
  bool success = 1;
  optional string error = 2;
  // output binary data, null when compression fails
  optional bytes compressed_video_bytes = 3;
}

service CompressionService {
  rpc Compress(CompressionRequest) returns (CompressionResponse);
}
