syntax = "proto3";

package compression.protobuf;

option csharp_namespace = "Compression.Protobuf";

enum Codec {
  H264 = 0;
  H265 = 1;
}

enum Format {
  MP4 = 0;
  MKV = 1;
  AVI = 3;
  FLV = 4;
  MOV = 5;
}

message CompressionRequest {
  // input binary data
  bytes video_bytes = 1;
  Format outputFormat = 2;
  Codec codec = 4;
}

message CompressionResponse {
  bool success = 1;
  optional string error = 2;
  // output binary data, null when compression fails
  optional bytes compressed_video_bytes = 3;
}

service CompressionService {
  rpc Compress(CompressionRequest) returns (CompressionResponse);
}
